# Config
# ===============================================================

# Language of your content in 2-letter code, e.g.: en, de.
lang: se

# The title of your page. Used in the sidebar and the browser tab.
title: Umeådyksällskap

# A list of keywords for your page
keywords: [dykning, dykträning, dykkurser, ssdf]

description: >
  Umeådyksällskap är en ideell förening ansluten till Svenska Sportdykarförbundet.

tagline: Upplev en värld under vattenytan.

# Sidebar image and theme color of the site.
accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
logo: /assets/img/logo.png

# This text will appear in a `<small>` tag in the footer of every page.
copyright: © 2024. All rights reserved.

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font: Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif

# Google fonts is disabled to prevent outgoing traffic
google_fonts: false

# Add links to the sidebar.
menu:
  - title: Bli medlem
    url: /medlemskap
  # - title: Blog
  #   url: /blog/
  - title: Dykplatser
    url: /dykplatser/
  # - title: Service
  #   url: /service/
  - title: Utbildning
    url: /utbildning/

# Pagination configuration (used by the `blog` layout)
paginate: 10
paginate_path: /blog/:num/

# Hydejack Settings
# ----------------------------------------------------------------------------------------
# These settings are specific to Hydejack.

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons: [about, newsletter, related, random, comments]

  # Configure the order of complementary content on project pages
  project_addons: [about, newsletter, other, comments]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external: false

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state: false

  # Set to `true` if you want to disable the drawer (left hand menue)
  no_drawer: true

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar: false

  # Set to true to disable the built-in search functionality.
  no_search: true

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css: false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis.
  no_page_style: true

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout: true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc: true

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column: true

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings: false

  # Set to `true` if you do not want to expose your resume and projects in machine-readable formats
  no_structured_data: false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color: false

  no_breadcrumbs: false

  use_lsi: true
  cookies_banner: false
  advertise: true
  hide_dates: false
  hide_last_modified: false

  dark_mode:
    always: false
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true

  offline:
    enabled: false
    cache_version: 1
    precache_assets:
      - /assets/img/swipe.svg

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all
  ignore:
    envs: [development]

sass:
  style: compressed

disable_disk_cache: true

remote_theme: hydecorp/hydejack@v9.2.1
